// House Accounts Auth API. Uses Supabase Auth + existing ha_users / ha_organizations tables.
function json(res,status,body){return res.status(status).json(body)}
function clean(v=''){return String(v||'').trim()}
function lower(v=''){return clean(v).toLowerCase()}
function appBaseUrl(req){
  const configured=clean(process.env.APP_BASE_URL);
  if(configured)return configured.replace(/\/+$/,'');
  const host=clean(req?.headers?.host);
  const isLocal=/^(localhost|127\.0\.0\.1)(:\d+)?$/i.test(host);
  if(isLocal)return `http://${host}`;
  return 'https://www.houseaccounts.ai';
}
function planConfig(planRaw){const plan=clean(planRaw||'free').toLowerCase();if(plan==='solo')return{plan:'solo',seat_limit:1};if(plan==='team')return{plan:'team',seat_limit:25};if(plan==='enterprise')return{plan:'enterprise',seat_limit:null};return{plan:'free',seat_limit:1}}
function orgDefaults(planRaw){const cfg=planConfig(planRaw);const now=new Date();if(cfg.plan==='solo'||cfg.plan==='team'){return{...cfg,trial_status:'active',subscription_status:'trialing',trial_started_at:now.toISOString(),trial_end:new Date(now.getTime()+30*86400000).toISOString(),trial_used:true}}if(cfg.plan==='enterprise'){return{...cfg,trial_status:'inactive',subscription_status:'manual',trial_started_at:null,trial_end:null,trial_used:false}}return{...cfg,trial_status:'inactive',subscription_status:'inactive',trial_started_at:null,trial_end:null,trial_used:false}}
function env(){const rawUrl=process.env.SUPABASE_URL;const key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!rawUrl||!key)throw new Error('Missing SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY');const url=String(rawUrl).trim().replace(/\/+$/,'').replace(/\/rest\/v1$/i,'');return{url,key}}
async function sb(path, options={}){const{url,key}=env();const resp=await fetch(`${url}/rest/v1/${path}`,{...options,headers:{apikey:key,Authorization:`Bearer ${key}`,'Content-Type':'application/json',Prefer:options.prefer||'return=representation',...(options.headers||{})}});const text=await resp.text();let data=null;if(text){try{data=JSON.parse(text)}catch{data=text}}if(!resp.ok){const msg=typeof data==='string'?data:(data?.message||data?.hint||JSON.stringify(data));throw new Error(`Supabase ${resp.status}: ${msg}`)}return data}
async function authFetch(path, options={}){const{url,key}=env();const resp=await fetch(`${url}/auth/v1/${path}`,{...options,headers:{apikey:key,Authorization:`Bearer ${key}`,'Content-Type':'application/json',...(options.headers||{})}});const text=await resp.text();let data={};if(text){try{data=JSON.parse(text)}catch{data={raw:text}}}if(!resp.ok){throw new Error(data.error_description||data.msg||data.error||data.message||`Supabase Auth ${resp.status}`)}return data}
async function getAuthUser(accessToken){if(!accessToken)return null;try{return await authFetch('user',{method:'GET',headers:{Authorization:`Bearer ${accessToken}`}})}catch{return null}}
async function getHaUserByAuth(authUserId){const rows=await sb(`ha_users?auth_user_id=eq.${encodeURIComponent(authUserId)}&select=*&limit=1`,{method:'GET'});return Array.isArray(rows)?rows[0]:null}
async function getHaUserByEmail(email){const rows=await sb(`ha_users?email=eq.${encodeURIComponent(email)}&select=*&limit=1`,{method:'GET'});return Array.isArray(rows)?rows[0]:null}
async function ensureOrgAndUser(authUser, profile={}){const email=lower(authUser?.email||profile.email);if(!email)throw new Error('Missing auth email');let user=authUser?.id?await getHaUserByAuth(authUser.id):null;if(!user)user=await getHaUserByEmail(email);let orgId=user?.organization_id||'';if(!orgId){const orgName=clean(profile.organizationName||profile.company||user?.company||email.split('@')[1]||'New Organization');const cfg=orgDefaults(profile.plan);const inserted=await sb('ha_organizations',{method:'POST',body:JSON.stringify([{name:orgName,plan:cfg.plan,trial_status:cfg.trial_status,subscription_status:cfg.subscription_status,trial_started_at:cfg.trial_started_at,trial_end:cfg.trial_end,trial_used:cfg.trial_used,seat_limit:cfg.seat_limit,created_at:new Date().toISOString(),updated_at:new Date().toISOString()}])});const org=Array.isArray(inserted)?inserted[0]:inserted;orgId=org?.id;if(!orgId)throw new Error('Organization create did not return an id.');}
const row={email,name:clean(profile.name||user?.name||authUser?.user_metadata?.name),company:clean(profile.organizationName||profile.company||user?.company),role:clean(profile.role||user?.role),house_accounts:clean(profile.house_accounts||profile.houseAccounts||user?.house_accounts),crm_erp:clean(profile.crm_erp||profile.crmErp||user?.crm_erp),auth_user_id:authUser.id,organization_id:orgId,app_role:user?.app_role||'owner',status:'active',updated_at:new Date().toISOString()};
if(user?.id){const updated=await sb(`ha_users?id=eq.${encodeURIComponent(user.id)}`,{method:'PATCH',body:JSON.stringify(row)});return Array.isArray(updated)?updated[0]:updated}
const created=await sb('ha_users',{method:'POST',body:JSON.stringify([{...row,created_at:new Date().toISOString()}])});return Array.isArray(created)?created[0]:created}
async function recordLogin(haUser, req){if(!haUser?.id)return;const prior=Number(haUser.login_count||0);const patch={last_login:new Date().toISOString(),last_seen_at:new Date().toISOString(),login_count:prior+1,user_agent:req.headers['user-agent']||'',last_ip:(req.headers['x-forwarded-for']||req.socket?.remoteAddress||'').toString().split(',')[0].trim(),updated_at:new Date().toISOString()};try{await sb(`ha_users?id=eq.${encodeURIComponent(haUser.id)}`,{method:'PATCH',body:JSON.stringify(patch),prefer:'return=minimal'})}catch(e){console.warn('[auth] login tracking skipped:',e.message)}}
function publicUser(authUser,haUser){return{id:haUser?.id||'',auth_user_id:authUser?.id||haUser?.auth_user_id||'',email:haUser?.email||authUser?.email||'',name:haUser?.name||authUser?.user_metadata?.name||'',company:haUser?.company||'',organization_id:haUser?.organization_id||'',app_role:haUser?.app_role||'',status:haUser?.status||''}}
export default async function handler(req,res){try{const action=req.method==='GET'?(req.query?.action||'me'):(req.body?.action||'');if(action==='signup'){const email=lower(req.body.email),password=clean(req.body.password);if(!email||!password)return json(res,400,{error:'Email and password are required.'});let authUser;try{authUser=await authFetch('admin/users',{method:'POST',body:JSON.stringify({email,password,email_confirm:true,user_metadata:{name:clean(req.body.name),organization_name:clean(req.body.organizationName),role:clean(req.body.role),house_accounts:clean(req.body.house_accounts||req.body.houseAccounts),crm_erp:clean(req.body.crm_erp||req.body.crmErp),plan:clean(req.body.plan)}})});}catch(err){if(String(err.message||'').toLowerCase().includes('already')){return json(res,409,{error:'An account already exists for this email. Please log in.'})}throw err}const haUser=await ensureOrgAndUser(authUser,{email,name:req.body.name,organizationName:req.body.organizationName,role:req.body.role,house_accounts:req.body.house_accounts||req.body.houseAccounts,crm_erp:req.body.crm_erp||req.body.crmErp,plan:req.body.plan});const data=await authFetch('token?grant_type=password',{method:'POST',body:JSON.stringify({email,password})});await recordLogin(haUser,req);return json(res,200,{ok:true,session:{access_token:data.access_token,refresh_token:data.refresh_token,expires_in:data.expires_in,expires_at:Math.floor(Date.now()/1000)+Number(data.expires_in||3600),token_type:data.token_type},user:publicUser(data.user||authUser,haUser)})}
if(action==='login'){const email=lower(req.body.email),password=clean(req.body.password);if(!email||!password)return json(res,400,{error:'Email and password are required.'});const data=await authFetch('token?grant_type=password',{method:'POST',body:JSON.stringify({email,password})});const authUser=data.user;const haUser=await ensureOrgAndUser(authUser,{email});await recordLogin(haUser,req);return json(res,200,{ok:true,session:{access_token:data.access_token,refresh_token:data.refresh_token,expires_in:data.expires_in,expires_at:Math.floor(Date.now()/1000)+Number(data.expires_in||3600),token_type:data.token_type},user:publicUser(authUser,haUser)})}
if(action==='refresh'){const refresh_token=clean(req.body.refresh_token);if(!refresh_token)return json(res,400,{error:'Missing refresh token.'});const data=await authFetch('token?grant_type=refresh_token',{method:'POST',body:JSON.stringify({refresh_token})});const haUser=await ensureOrgAndUser(data.user,{email:data.user?.email});return json(res,200,{ok:true,session:{access_token:data.access_token,refresh_token:data.refresh_token||refresh_token,expires_in:data.expires_in,expires_at:Math.floor(Date.now()/1000)+Number(data.expires_in||3600),token_type:data.token_type},user:publicUser(data.user,haUser)})}
if(action==='recover'){const email=lower(req.body.email);if(!email)return json(res,400,{error:'Email is required.'});const redirectTo=`${appBaseUrl(req)}/update-password`;await authFetch(`recover?redirect_to=${encodeURIComponent(redirectTo)}`,{method:'POST',body:JSON.stringify({email})});return json(res,200,{ok:true})}
if(action==='update-password'){const auth=req.headers.authorization||'';const password=clean(req.body.password);if(!auth||!password)return json(res,400,{error:'Missing session or password.'});const data=await authFetch('user',{method:'PUT',headers:{Authorization:auth},body:JSON.stringify({password})});return json(res,200,{ok:true,user:data})}
if(action==='logout'){return json(res,200,{ok:true})}
if(action==='me'){const auth=(req.headers.authorization||'').replace(/^Bearer\s+/i,'');const authUser=await getAuthUser(auth);if(!authUser?.id)return json(res,401,{error:'Not authenticated'});const haUser=await ensureOrgAndUser(authUser,{email:authUser.email});return json(res,200,{ok:true,user:publicUser(authUser,haUser)})}
return json(res,400,{error:'Unknown auth action.'})}catch(err){return json(res,500,{error:err.message||'Auth failed'})}}
