function json(res,status,body){res.setHeader('Cache-Control','no-store, max-age=0');return res.status(status).json(body)}
function clean(v=''){return String(v||'').trim()}
function lower(v=''){return clean(v).toLowerCase()}
function normCompany(v=''){return lower(v).replace(/^https?:\/\//,'').replace(/^www\./,'').replace(/\/+$/,'').replace(/\b(incorporated|inc|llc|ltd|limited|corp|corporation|co|company)\b\.?/g,'').replace(/[^a-z0-9]+/g,' ').trim()}
function env(){const raw=process.env.SUPABASE_URL,key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!raw||!key)throw new Error('Missing SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY');return{url:String(raw).trim().replace(/\/+$/,'').replace(/\/rest\/v1$/i,''),key}}
async function sb(path,opt={}){const{url,key}=env();const r=await fetch(`${url}/rest/v1/${path}`,{...opt,headers:{apikey:key,Authorization:`Bearer ${key}`,'Content-Type':'application/json',Prefer:opt.prefer||'return=representation',...(opt.headers||{})}});const t=await r.text();let d=null;if(t){try{d=JSON.parse(t)}catch{d=t}}if(!r.ok)throw new Error(`Supabase ${r.status}: ${typeof d==='string'?d:(d?.message||d?.hint||JSON.stringify(d))}`);return d}
async function authUser(req){const token=String(req.headers.authorization||'').replace(/^Bearer\s+/i,'');if(!token)return null;const{url,key}=env();const r=await fetch(`${url}/auth/v1/user`,{headers:{apikey:key,Authorization:`Bearer ${token}`}});if(!r.ok)return null;return r.json()}
async function context(req){const au=await authUser(req);if(!au?.id)return null;let rows=await sb(`ha_users?auth_user_id=eq.${encodeURIComponent(au.id)}&select=*&limit=1`);let user=Array.isArray(rows)?rows[0]:null;if(!user&&au.email){rows=await sb(`ha_users?email=eq.${encodeURIComponent(lower(au.email))}&select=*&limit=1`);user=Array.isArray(rows)?rows[0]:null}if(!user)return null;const orgRows=user.organization_id?await sb(`ha_organizations?id=eq.${encodeURIComponent(user.organization_id)}&select=*&limit=1`):[];const org=Array.isArray(orgRows)?orgRows[0]:null;const users=user.organization_id?await sb(`ha_users?organization_id=eq.${encodeURIComponent(user.organization_id)}&select=id,email,status`):[user];const active=(Array.isArray(users)?users:[]).filter(x=>lower(x.status||'active')!=='inactive');return{user,org,userIds:active.map(x=>x.id).filter(Boolean),emails:active.map(x=>lower(x.email)).filter(Boolean)}}
function inFilter(vals){return `in.(${vals.map(v=>`\"${String(v).replace(/\"/g,'')}\"`).join(',')})`}
function signalType(s={}){return clean(s.signal_type||s.signalType||s.type||s.opportunityType||'Business Activity')}
function signalTitle(s={}){return clean(s.concrete_trigger||s.concreteTrigger||s.buying_moment||s.buyingMoment||s.title||s.signalTitle||s.headline||'Business activity signal')}
function signalSummary(s={}){return clean(s.summary||s.business_context||s.businessContext||s.why_this_matters||s.whyThisMatters||s.whyItMattersForPromo||s.reasonToReachOut||s.signalDetail)}
function sourceUrl(s={}){return clean(s.source_url||s.sourceUrl||s.url||(Array.isArray(s.sources)?s.sources[0]?.url:''))}
function sourceName(s={}){return clean(s.source_name||s.sourceName||s.cleanSourceName||s.sourceDomain||s.sourceType||(Array.isArray(s.sources)?s.sources[0]?.name||s.sources[0]?.title:''))}
function num(v){const n=Number(v);return Number.isFinite(n)?(n<=1?Math.round(n*100):Math.round(n)):null}
async function monitoredContext(ctx){const ids=ctx.userIds.length?inFilter(ctx.userIds):'eq.__none__';const emails=ctx.emails.length?inFilter(ctx.emails):'eq.__none__';const [uploads,pUploads]=await Promise.all([sb(`ha_uploads?user_id=${ids}&select=id,stage&limit=5000`),sb(`ha_prospect_uploads?user_email=${emails}&select=id,status&limit=5000`)]);const activeUploadIds=(uploads||[]).filter(u=>!['paused','archived'].includes(lower(u.stage))).map(u=>u.id);const activeProspectUploadIds=(pUploads||[]).filter(u=>!['paused','archived'].includes(lower(u.status))).map(u=>u.id);let customer=[],prospects=[];if(activeUploadIds.length)customer=await sb(`ha_accounts?upload_id=${inFilter(activeUploadIds)}&select=account_name&limit=10000`);if(activeProspectUploadIds.length)prospects=await sb(`ha_prospect_accounts?upload_id=${inFilter(activeProspectUploadIds)}&select=company_name,id,upload_id&limit=10000`);const names=new Set([...(customer||[]).map(x=>normCompany(x.account_name)),...(prospects||[]).map(x=>normCompany(x.company_name))].filter(Boolean));const plan=lower(ctx.org?.plan||'free');const trialing=lower(ctx.org?.subscription_status)==='trialing'&&ctx.org?.trial_end&&new Date(ctx.org.trial_end)>new Date();const activePaid=['solo','team','enterprise'].includes(plan)&&(trialing||lower(ctx.org?.subscription_status)==='active');const limited=plan==='free'||(!activePaid&&['solo','team'].includes(plan));return{names,used:names.size,limited,limit:limited?10:null,prospects}}
export default async function handler(req,res){try{if(req.method!=='POST')return json(res,405,{error:'POST only'});const ctx=await context(req);if(!ctx)return json(res,401,{error:'Authentication required'});const body=req.body||{};const companyName=clean(body.companyName||body.name);const website=clean(body.website);const normalized=normCompany(companyName||website);if(!normalized)return json(res,400,{error:'Company name or website is required'});const usage=await monitoredContext(ctx);const existing=usage.prospects.find(p=>normCompany(p.company_name)===normalized);if(existing)return json(res,200,{ok:true,alreadyMonitored:true,prospectAccountId:existing.id,message:'Already monitored'});if(usage.limited&&usage.used>=usage.limit)return json(res,403,{error:`You’re monitoring ${usage.limit} companies for free. Upgrade to unlock the rest and enable ongoing monitoring.`,limitReached:true});const now=new Date().toISOString();const uploads=await sb('ha_prospect_uploads',{method:'POST',body:JSON.stringify([{user_email:lower(ctx.user.email),filename:`One-off research — ${companyName||website}`,account_count:1,status:'active',created_at:now}])});const upload=Array.isArray(uploads)?uploads[0]:uploads;if(!upload?.id)throw new Error('Prospect upload insert did not return an id');const accounts=await sb('ha_prospect_accounts',{method:'POST',body:JSON.stringify([{upload_id:upload.id,company_name:companyName||website,website,industry:clean(body.industry),location:clean(body.location),status:'active',last_scanned_at:now,created_at:now}])});const account=Array.isArray(accounts)?accounts[0]:accounts;if(!account?.id)throw new Error('Prospect account insert did not return an id');const signals=Array.isArray(body.signals)?body.signals:[];const rows=signals.map(s=>({prospect_account_id:account.id,upload_id:upload.id,user_email:lower(ctx.user.email),company_name:companyName||website,signal_type:signalType(s),title:signalTitle(s),summary:signalSummary(s),source_url:sourceUrl(s),source_name:sourceName(s),confidence_score:num(s.confidence_score??s.confidenceScore??s.confidence),why_now_score:num(s.why_now_score??s.whyNowScore??s.whyNow??s.score),suggested_opener:clean(s.suggested_opener||s.suggestedOpener||s.opener||s.recommendedNextStep),created_at:now}));if(rows.length)await sb('ha_prospect_signals',{method:'POST',body:JSON.stringify(rows)});console.log(`One-off prospect saved successfully: ${companyName||website}, ${rows.length} signals.`);return json(res,200,{ok:true,alreadyMonitored:false,uploadId:upload.id,prospectAccountId:account.id,signalsSaved:rows.length})}catch(e){console.error('[One-off Prospect Save]',e);return json(res,500,{error:e.message||'Could not save prospect'})}}
