function json(res,status,body){return res.status(status).json(body)}
function clean(v=''){return String(v||'').trim()}
function env(){const rawUrl=process.env.SUPABASE_URL;const key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!rawUrl||!key)throw new Error('Missing SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY');const url=String(rawUrl).trim().replace(/\/+$/,'').replace(/\/rest\/v1$/i,'');return{url,key}}
async function sb(path, options={}){const{url,key}=env();const resp=await fetch(`${url}/rest/v1/${path}`,{...options,headers:{apikey:key,Authorization:`Bearer ${key}`,'Content-Type':'application/json',Prefer:options.prefer||'return=representation',...(options.headers||{})}});const text=await resp.text();let data=null;if(text){try{data=JSON.parse(text)}catch{data=text}}if(!resp.ok){const msg=typeof data==='string'?data:(data?.message||JSON.stringify(data));throw new Error(`Supabase ${resp.status}: ${msg}`)}return {data,headers:resp.headers}}
async function authUser(req){const token=(req.headers.authorization||'').replace(/^Bearer\s+/i,'');if(!token)return null;const{url,key}=env();const resp=await fetch(`${url}/auth/v1/user`,{headers:{apikey:key,Authorization:`Bearer ${token}`}});if(!resp.ok)return null;return resp.json()}
async function haUser(req){const au=await authUser(req);if(!au?.id)return null;const {data}=await sb(`ha_users?auth_user_id=eq.${encodeURIComponent(au.id)}&select=*&limit=1`);return Array.isArray(data)?data[0]:null}
function uniqueCount(rows, field){return new Set((rows||[]).map(r=>clean(r[field]).toLowerCase()).filter(Boolean)).size}
async function orgUsers(orgId,userId){if(orgId){const {data}=await sb(`ha_users?organization_id=eq.${encodeURIComponent(orgId)}&select=id`);return (data||[]).map(u=>u.id).filter(Boolean)}return [userId].filter(Boolean)}
async function usageFor(user){const ids=await orgUsers(user.organization_id,user.id);const inFilter=`in.(${ids.map(encodeURIComponent).join(',')})`;let customer=[],prospect=[];try{customer=(await sb(`ha_accounts?user_id=${inFilter}&select=account_name`)).data||[]}catch{}try{prospect=(await sb(`ha_prospect_accounts?user_id=${inFilter}&select=company_name`)).data||[]}catch{}const names=new Set([...customer.map(r=>clean(r.account_name).toLowerCase()),...prospect.map(r=>clean(r.company_name).toLowerCase())].filter(Boolean));return{customerCompanyCount:uniqueCount(customer,'account_name'),prospectCompanyCount:uniqueCount(prospect,'company_name'),totalMonitoredCompanies:names.size,freeCompanyLimit:10}}
export default async function handler(req,res){if(req.method!=='GET')return json(res,405,{error:'Method not allowed'});try{const user=await haUser(req);if(!user)return json(res,401,{error:'Not authenticated'});let org=null;if(user.organization_id){const {data}=await sb(`ha_organizations?id=eq.${encodeURIComponent(user.organization_id)}&select=*&limit=1`);org=Array.isArray(data)?data[0]:null}const usage=await usageFor(user);return json(res,200,{user,organization:org,usage})}catch(err){return json(res,500,{error:err.message||'Settings failed'})}}
