function json(res,status,body){res.setHeader('Cache-Control','no-store, max-age=0');return res.status(status).json(body)}
function clean(v=''){return String(v||'').trim()}
function env(){const rawUrl=process.env.SUPABASE_URL;const key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!rawUrl||!key)throw new Error('Missing SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY');const url=String(rawUrl).trim().replace(/\/+$/,'').replace(/\/rest\/v1$/i,'');return{url,key}}
async function sb(path, options={}){const{url,key}=env();const resp=await fetch(`${url}/rest/v1/${path}`,{...options,headers:{apikey:key,Authorization:`Bearer ${key}`,'Content-Type':'application/json',Prefer:options.prefer||'return=representation',...(options.headers||{})}});const text=await resp.text();let data=null;if(text){try{data=JSON.parse(text)}catch{data=text}}if(!resp.ok){const msg=typeof data==='string'?data:(data?.message||JSON.stringify(data));throw new Error(`Supabase ${resp.status}: ${msg}`)}return {data,headers:resp.headers}}
async function authUser(req){const token=(req.headers.authorization||'').replace(/^Bearer\s+/i,'');if(!token)return null;const{url,key}=env();const resp=await fetch(`${url}/auth/v1/user`,{headers:{apikey:key,Authorization:`Bearer ${token}`}});if(!resp.ok)return null;return resp.json()}
async function haUser(req){const au=await authUser(req);if(!au?.id)return null;const {data}=await sb(`ha_users?auth_user_id=eq.${encodeURIComponent(au.id)}&select=*&limit=1`);return Array.isArray(data)?data[0]:null}
function uniqueCount(rows, field){return new Set((rows||[]).map(r=>clean(r[field]).toLowerCase()).filter(Boolean)).size}
async function orgUsers(orgId,userId){if(orgId){const {data}=await sb(`ha_users?organization_id=eq.${encodeURIComponent(orgId)}&select=id`);return (data||[]).map(u=>u.id).filter(Boolean)}return [userId].filter(Boolean)}
async function usageFor(user, org=null){const ids=await orgUsers(user.organization_id,user.id);const inFilter=`in.(${ids.map(encodeURIComponent).join(',')})`;let customer=[],prospect=[],legacyMonitored=[];try{customer=(await sb(`ha_accounts?user_id=${inFilter}&select=account_name`)).data||[]}catch{}try{prospect=(await sb(`ha_prospect_accounts?user_id=${inFilter}&select=company_name`)).data||[]}catch{}try{legacyMonitored=(await sb(`ha_monitored_companies?user_id=${inFilter}&select=company_name,name,account_name`)).data||[]}catch{}const normalizeName=v=>clean(v).toLowerCase().replace(/\b(incorporated|inc|llc|ltd|limited|corp|corporation|co|company)\b\.?/g,'').replace(/[^a-z0-9]+/g,' ').trim();const customerNames=new Set(customer.map(r=>normalizeName(r.account_name)).filter(Boolean));const prospectNames=new Set(prospect.map(r=>normalizeName(r.company_name)).filter(Boolean));const legacyNames=new Set(legacyMonitored.map(r=>normalizeName(r.company_name||r.name||r.account_name)).filter(Boolean));const names=new Set([...customerNames,...prospectNames]);const plan=clean(org?.plan||'free').toLowerCase();const freeCompanyLimit=10;const companyLimit=plan==='free'?freeCompanyLimit:null;return{customerCompanyCount:customerNames.size,existingCustomerCompanyCount:customerNames.size,prospectCompanyCount:prospectNames.size,legacyMonitoredCompanyCount:legacyNames.size,totalMonitoredCompanies:names.size,freeCompanyLimit,companyLimit,isFreePlan:plan==='free',monitoredCompanyNames:[...names],customerCompanyNames:[...customerNames],prospectCompanyNames:[...prospectNames]}}
function planConfig(planRaw){const plan=clean(planRaw||'free').toLowerCase();if(plan==='solo')return{plan:'solo',seat_limit:1};if(plan==='team')return{plan:'team',seat_limit:25};if(plan==='enterprise')return{plan:'enterprise',seat_limit:null};return{plan:'free',seat_limit:1}}
async function loadOrg(user){if(!user?.organization_id)return null;const {data}=await sb(`ha_organizations?id=eq.${encodeURIComponent(user.organization_id)}&select=*&limit=1`);return Array.isArray(data)?data[0]:null}
export default async function handler(req,res){try{const user=await haUser(req);if(!user)return json(res,401,{error:'Not authenticated'});if(req.method==='GET'){const org=await loadOrg(user);const usage=await usageFor(user, org);return json(res,200,{user,organization:org,usage})}if(req.method==='POST'){const action=clean(req.body?.action||'');if(action!=='update-plan')return json(res,400,{error:'Unknown settings action.'});if(!user.organization_id)return json(res,400,{error:'User is not linked to an organization.'});const cfg=planConfig(req.body?.plan);const patch={plan:cfg.plan,seat_limit:cfg.seat_limit,updated_at:new Date().toISOString()};const {data}=await sb(`ha_organizations?id=eq.${encodeURIComponent(user.organization_id)}`,{method:'PATCH',body:JSON.stringify(patch)});const org=Array.isArray(data)?data[0]:data;const usage=await usageFor(user, org);return json(res,200,{ok:true,organization:org,usage})}return json(res,405,{error:'Method not allowed'})}catch(err){return json(res,500,{error:err.message||'Settings failed'})}}
