function json(res,status,body){res.setHeader('Cache-Control','no-store, max-age=0');return res.status(status).json(body)}
function clean(v=''){return String(v||'').trim()}
function lower(v=''){return clean(v).toLowerCase()}
function appBaseUrl(req){const configured=clean(process.env.APP_BASE_URL||process.env.PUBLIC_APP_URL);if(configured)return configured.replace(/\/+$/,'');const host=clean(req?.headers?.host);if(/^(localhost|127\.0\.0\.1)(:\d+)?$/i.test(host))return `http://${host}`;return 'https://www.houseaccounts.ai'}
function escapeHtml(v=''){return String(v||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;')}
function env(){const rawUrl=process.env.SUPABASE_URL;const key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!rawUrl||!key)throw new Error('Missing SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY');const url=String(rawUrl).trim().replace(/\/+$/,'').replace(/\/rest\/v1$/i,'');return{url,key}}
async function sb(path, options={}){const{url,key}=env();const resp=await fetch(`${url}/rest/v1/${path}`,{...options,headers:{apikey:key,Authorization:`Bearer ${key}`,'Content-Type':'application/json',Prefer:options.prefer||'return=representation',...(options.headers||{})}});const text=await resp.text();let data=null;if(text){try{data=JSON.parse(text)}catch{data=text}}if(!resp.ok){const msg=typeof data==='string'?data:(data?.message||data?.hint||JSON.stringify(data));throw new Error(`Supabase ${resp.status}: ${msg}`)}return data}
async function authFetch(path, options={}){const{url,key}=env();const resp=await fetch(`${url}/auth/v1/${path}`,{...options,headers:{apikey:key,Authorization:`Bearer ${key}`,'Content-Type':'application/json',...(options.headers||{})}});const text=await resp.text();let data={};if(text){try{data=JSON.parse(text)}catch{data={raw:text}}}if(!resp.ok){throw new Error(data.error_description||data.msg||data.error||data.message||`Supabase Auth ${resp.status}`)}return data}
async function authUser(req){const token=(req.headers.authorization||'').replace(/^Bearer\s+/i,'');if(!token)return null;try{return await authFetch('user',{method:'GET',headers:{Authorization:`Bearer ${token}`}})}catch{return null}}
async function haUser(req){const au=await authUser(req);if(!au?.id)return null;const rows=await sb(`ha_users?auth_user_id=eq.${encodeURIComponent(au.id)}&select=*&limit=1`,{method:'GET'});return Array.isArray(rows)?rows[0]:null}
async function orgFor(user){if(!user?.organization_id)return null;const rows=await sb(`ha_organizations?id=eq.${encodeURIComponent(user.organization_id)}&select=*&limit=1`,{method:'GET'});return Array.isArray(rows)?rows[0]:null}
function isAdmin(user){const role=lower(user?.app_role||user?.role);return role==='owner'||role==='admin'}
async function activeUsers(orgId){const rows=await sb(`ha_users?organization_id=eq.${encodeURIComponent(orgId)}&select=id,name,email,app_role,role,status,created_at,last_login&order=created_at.asc`,{method:'GET'});return (rows||[]).filter(u=>lower(u.status||'active')!=='inactive')}
async function pendingInvites(orgId){const rows=await sb(`ha_invitations?organization_id=eq.${encodeURIComponent(orgId)}&status=eq.pending&select=*&order=created_at.desc`,{method:'GET'});const now=Date.now();return (rows||[]).filter(i=>{const t=new Date(i.expires_at||0).getTime();return !t||t>now})}
function seatLimit(org){const raw=org?.seat_limit;if(raw===null||raw===undefined||raw==='')return null;const n=Number(raw);return Number.isFinite(n)?n:null}
function hasSeat(limit, used, pending){return limit===null || (used+pending)<limit}
function token(){const bytes=new Uint8Array(24);crypto.getRandomValues(bytes);return Array.from(bytes,b=>b.toString(16).padStart(2,'0')).join('')}
async function sendInviteEmail({to, orgName, token, inviterName, inviterEmail, baseUrl}){const key=process.env.RESEND_API_KEY;if(!key)throw new Error('Missing RESEND_API_KEY');const from=process.env.RESEND_FROM_EMAIL||process.env.ALERTS_FROM_EMAIL||'House Accounts <hello@houseaccounts.ai>';const base=clean(baseUrl)||'https://www.houseaccounts.ai';const link=`${String(base).replace(/\/+$/,'')}/accept-invite?token=${encodeURIComponent(token)}`;const inviter=clean(inviterName)||clean(inviterEmail);const inviterLine=inviter?`<p style="margin:0 0 16px;color:#5f6f86;">Invited by ${escapeHtml(inviter)}${inviterEmail&&inviter!==inviterEmail?` (${escapeHtml(inviterEmail)})`:''}.</p>`:'';const subject=`You’ve been invited to join ${orgName} on House Accounts`;const html=`<div style="font-family:Arial,sans-serif;line-height:1.5;color:#17375E;max-width:560px;"><h2 style="margin:0 0 12px;">You’ve been invited to House Accounts</h2><p>You’ve been invited to join <strong>${escapeHtml(orgName)}</strong> on House Accounts.</p>${inviterLine}<p><a href="${escapeHtml(link)}" style="display:inline-block;background:#F5A623;color:#1f2937;text-decoration:none;padding:12px 18px;border-radius:10px;font-weight:800;">Accept invitation</a></p><p style="color:#5f6f86;font-size:13px;">This invite expires in 7 days.</p><p style="color:#5f6f86;font-size:13px;">If the button does not work, copy and paste this link into your browser:<br>${escapeHtml(link)}</p></div>`;const resp=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:`Bearer ${key}`,'Content-Type':'application/json'},body:JSON.stringify({from,to,subject,html})});const data=await resp.json().catch(()=>({}));if(!resp.ok)throw new Error(`Resend ${resp.status}: ${data.message||JSON.stringify(data)}`);return data}
async function getInviteByToken(rawToken){const t=clean(rawToken);if(!t)return null;const rows=await sb(`ha_invitations?token=eq.${encodeURIComponent(t)}&select=*&limit=1`,{method:'GET'});return Array.isArray(rows)?rows[0]:null}
async function createSession(email,password){const data=await authFetch('token?grant_type=password',{method:'POST',body:JSON.stringify({email,password})});return {access_token:data.access_token,refresh_token:data.refresh_token,expires_in:data.expires_in,expires_at:Math.floor(Date.now()/1000)+Number(data.expires_in||3600),token_type:data.token_type}}
export default async function handler(req,res){try{const action=req.method==='GET'?clean(req.query?.action||'list'):clean(req.body?.action||'');
 if(action==='validate-invite'){const inv=await getInviteByToken(req.query?.token);if(!inv)return json(res,404,{error:'Invitation not found.'});if(lower(inv.status)!=='pending')return json(res,400,{error:'This invitation is no longer pending.'});if(new Date(inv.expires_at||0).getTime()<=Date.now())return json(res,400,{error:'This invitation has expired.'});const orgRows=await sb(`ha_organizations?id=eq.${encodeURIComponent(inv.organization_id)}&select=id,name,seat_limit,plan&limit=1`,{method:'GET'});const org=Array.isArray(orgRows)?orgRows[0]:null;if(!org)return json(res,404,{error:'Organization not found.'});return json(res,200,{ok:true,invitation:{email:inv.email,role:inv.role||'member',expires_at:inv.expires_at},organization:{id:org.id,name:org.name,plan:org.plan,seat_limit:org.seat_limit}})}
 if(action==='accept-invite'){if(req.method!=='POST')return json(res,405,{error:'Method not allowed'});const inv=await getInviteByToken(req.body?.token);if(!inv)return json(res,404,{error:'Invitation not found.'});if(lower(inv.status)!=='pending')return json(res,400,{error:'This invitation is no longer pending.'});if(new Date(inv.expires_at||0).getTime()<=Date.now())return json(res,400,{error:'This invitation has expired.'});const orgRows=await sb(`ha_organizations?id=eq.${encodeURIComponent(inv.organization_id)}&select=*&limit=1`,{method:'GET'});const org=Array.isArray(orgRows)?orgRows[0]:null;if(!org)return json(res,404,{error:'Organization not found.'});const users=await activeUsers(org.id);const limit=seatLimit(org);if(limit!==null&&users.length>=limit)return json(res,403,{error:`This plan includes ${limit} seats. Upgrade to add more teammates.`});const email=lower(inv.email);const existing=await sb(`ha_users?email=eq.${encodeURIComponent(email)}&select=id,organization_id&limit=1`,{method:'GET'});if(Array.isArray(existing)&&existing[0])return json(res,409,{error:'An account already exists for this email. Please log in to accept your invitation.'});const name=clean(req.body?.name), password=clean(req.body?.password);if(!name||!password)return json(res,400,{error:'Name and password are required.'});let authUser;try{authUser=await authFetch('admin/users',{method:'POST',body:JSON.stringify({email,password,email_confirm:true,user_metadata:{name,invited_organization_id:org.id}})});}catch(err){if(String(err.message||'').toLowerCase().includes('already'))return json(res,409,{error:'An account already exists for this email. Please log in to accept your invitation.'});throw err}const created=await sb('ha_users',{method:'POST',body:JSON.stringify([{email,name,company:org.name,auth_user_id:authUser.id,organization_id:org.id,app_role:inv.role||'member',role:inv.role||'member',status:'active',created_at:new Date().toISOString(),updated_at:new Date().toISOString()}])});await sb(`ha_invitations?id=eq.${encodeURIComponent(inv.id)}`,{method:'PATCH',body:JSON.stringify({status:'accepted',accepted_at:new Date().toISOString()})});const session=await createSession(email,password);return json(res,200,{ok:true,session,user:Array.isArray(created)?created[0]:created})}
 const user=await haUser(req);if(!user)return json(res,401,{error:'Not authenticated'});const org=await orgFor(user);if(!org)return json(res,400,{error:'User is not linked to an organization.'});if(!isAdmin(user))return json(res,403,{error:'Only organization owners/admins can manage teammates.'});
 if(action==='list'){const [users,invites]=await Promise.all([activeUsers(org.id),pendingInvites(org.id)]);const limit=seatLimit(org);return json(res,200,{ok:true,organization:{id:org.id,name:org.name,plan:org.plan,seat_limit:org.seat_limit},users,pendingInvitations:invites,seatsUsed:users.length,pendingInviteCount:invites.length,seatLimit:limit})}
 if(action==='invite'){if(req.method!=='POST')return json(res,405,{error:'Method not allowed'});const email=lower(req.body?.email);const role=lower(req.body?.role||'member')||'member';if(!email)return json(res,400,{error:'Email is required.'});const [users,invites]=await Promise.all([activeUsers(org.id),pendingInvites(org.id)]);const limit=seatLimit(org);if(!hasSeat(limit,users.length,invites.length))return json(res,403,{error:`This plan includes ${limit} seats. Upgrade to add more teammates.`});const existing=await sb(`ha_users?email=eq.${encodeURIComponent(email)}&select=id&limit=1`,{method:'GET'});if(Array.isArray(existing)&&existing[0])return json(res,409,{error:'An account already exists for this email. Ask them to log in before accepting an invitation.'});const dup=invites.find(i=>lower(i.email)===email);if(dup)return json(res,409,{error:'This email already has a pending invitation.'});const inviteToken=token();const expires=new Date(Date.now()+7*86400000).toISOString();const inserted=await sb('ha_invitations',{method:'POST',body:JSON.stringify([{organization_id:org.id,email,role,status:'pending',token:inviteToken,expires_at:expires,created_by:user.id,created_at:new Date().toISOString()}])});let emailResult=null;try{emailResult=await sendInviteEmail({to:email,orgName:org.name||'your organization',token:inviteToken,inviterName:user.name,inviterEmail:user.email,baseUrl:appBaseUrl(req)});}catch(emailErr){console.error('[Team Invite] Resend email failed',{inviteEmail:email,organizationId:org.id,error:emailErr.message||emailErr});return json(res,502,{ok:false,invitation:Array.isArray(inserted)?inserted[0]:inserted,error:'Invitation was created, but the email could not be sent. The invite remains pending. Please try again or contact support.',details:emailErr.message||'Resend send failed'});}return json(res,200,{ok:true,invitation:Array.isArray(inserted)?inserted[0]:inserted,email:emailResult})}
 return json(res,400,{error:'Unknown team action.'})}catch(err){return json(res,err.status||500,{error:err.message||'Team request failed'})}}
